version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 1883:1883
      - 15672:15672
    volumes:
      - ./server/conf/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./server/conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: always

  database:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    restart: always

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    user: '472'
    volumes:
      - /var/lib/grafana:/var/lib/grafana
    restart: always

volumes:
  enabled_plugins:
  conf:
  postgresql:
  grafana:
