version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  database:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000

volumes:
  conf:
